### ISSUE TITLE
Bug: Python package not working?

### ISSUE THREAD

**Issue by ashutoshsaboo** [echo724/notion2md#16]
Hi @echo724 , I just installed this python package and it doesn't seem to work in the latest version. I installed the latest version from here - https://pypi.org/project/notion2md/2.2.2/ - and tried replicating what was mentioned in the README. Can you please help check what's going wrong here @echo724 - seems like a bug? 

The import error is this - `ImportError: cannot import name 'notion_client_object' from 'notion2md.client_handler' (/Users/macos/opt/anaconda3/lib/python3.8/site-packages/notion2md/client_handler.py)`. 

See detailed stack-trace below with installation logs as well: 

```
(base) macos@88665a14b29c scripts % pip install notion2md==2.2.2
Collecting notion2md==2.2.2
  Using cached notion2md-2.2.2-py3-none-any.whl (7.5 kB)
Requirement already satisfied: notion-client>=0.7.1 in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from notion2md==2.2.2) (0.8.0)
Requirement already satisfied: httpx>=0.15.0 in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from notion-client>=0.7.1->notion2md==2.2.2) (0.21.1)
Requirement already satisfied: sniffio in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (1.2.0)
Requirement already satisfied: httpcore<0.15.0,>=0.14.0 in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (0.14.3)
Requirement already satisfied: charset-normalizer in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (2.0.9)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (1.5.0)
Requirement already satisfied: certifi in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (2020.12.5)
Requirement already satisfied: anyio==3.* in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpcore<0.15.0,>=0.14.0->httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (3.4.0)
Requirement already satisfied: h11<0.13,>=0.11 in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from httpcore<0.15.0,>=0.14.0->httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (0.12.0)
Requirement already satisfied: idna>=2.8 in /Users/macos/opt/anaconda3/lib/python3.8/site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.0->httpx>=0.15.0->notion-client>=0.7.1->notion2md==2.2.2) (2.10)
Installing collected packages: notion2md
Successfully installed notion2md-2.2.2
(base) macos@88665a14b29c scripts % python
Python 3.8.8 (default, Apr 13 2021, 12:59:45)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from notion2md.exporter import block_exporter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macos/opt/anaconda3/lib/python3.8/site-packages/notion2md/exporter.py", line 1, in <module>
    from notion2md.client_handler import notion_client_object
ImportError: cannot import name 'notion_client_object' from 'notion2md.client_handler' (/Users/macos/opt/anaconda3/lib/python3.8/site-packages/notion2md/client_handler.py)
>>>
>>> #output_path is optional
>>> block_exporter("id of notion page","OutPut Path(Relative)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'block_exporter' is not defined
>>>
```

**Comment by echo724** [comment]
Did you export your Notion integration api key as your env variable named "NOTION_TOKEN"? It seems like there was an error when creating notion client object from api key. I will fix showing the error message when it happens. Thanks!

**Comment by ashutoshsaboo** [comment]
I did that @echo724 and the first part worked! Thanks! However there seems to be one small limitation as well, for page blocks with url in their titles, ex: `https://google.com/` (I clip certain pages to my notion, so in that case the title is set to url in some cases). In that case, your script tries to download the markdown file at `<input PATH prefix folder>/https://google.com/-<notion_block_id>`. Basically it doesn't escape the urls, so it errors out saying `FileNotFoundError: [Errno 2] No such file or directory:` - i.e, since the `http` part in url - dir for that doesn't exist. 

If possible, can you just use the `<notion block id>.md` as the filename so you don't have to deal with all these scenarios so this gets fixed? @echo724

**Comment by echo724** [comment]
Thank you for the great recommendation. As you said, if the title of the block is not supported as dir name, it will crush. I will fix this. Thank you
