### ISSUE TITLE
Returning empty markdown files

### ISSUE THREAD

**Issue by vtasca** [echo724/notion2md#39]
Having a bit of an issue getting the generated markdown files to work. I followed the example in the readme, and added my API key to an environment variable:
```
from notion2md.exporter.block import MarkdownExporter
from dotenv import load_dotenv
load_dotenv()
MarkdownExporter(block_id='my_block_id',output_path='test.md',download=True).export()
```

In this case, I'm getting the `page` directory generated, but the .md file inside is unfortunately empty. Do you know what could be causing this?

For reference, I'm using Python 3.9.13 and these Notion libraries:
```
notion-client==1.0.0
notion2md==2.7.6
```

**Comment by echo724** [comment]
I think the update of notion-client made the issue. Please check it again because I updated notion2md to support the update of notion-client. Thank you

**Comment by vtasca** [comment]
Thanks for the update, unfortunately I'm unable to upgrade as your dependencies require `notion-client>=1.0.1` and at the time of writing the latest version of this package is `1.0.0`. The [npm version](https://www.npmjs.com/package/@cyrus25/notion-client) is `1.0.1`, but not the [PyPI version](https://pypi.org/project/notion-client/).

**Comment by echo724** [comment]
I fixed it but I mentioned different issue... my bad. I upgraded the notion2md, so please reinstall notion2md. Again, I apologize to mention the wrong issue number. Thank you for making this issue
