### ISSUE TITLE
ERROR 'text'

### ISSUE THREAD

**Issue by rdevriese** [echo724/notion2md#40]
Running notion2md results in error statement: ERROR 'text'

Using notion2md version 2.7.6
Ubuntu 20.04
Python version 3.8.10

Notion page content (exported to markdown)
[Test page 19d3bdf4aade48438defa1b44d18031a.md](https://github.com/echo724/notion2md/files/9096067/Test.page.19d3bdf4aade48438defa1b44d18031a.md)

I've also tried calling the StringExporter() function from within a Python script and get the exact same error.
Traceback ends at line 39 with KeyError: 'text'

**Comment by liuyixin-louis** [comment]
I meet a similar question too. Looking for an answer.

**Comment by mxro** [comment]
I am getting the same error too for two different pages.

**Comment by rosenkim** [comment]
I also had that error and luckily found a solution.
The error did not occur when using notion-library 0.9.0
