### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pyMixin** [echo724/notion2md#44]
Getting error:
ERROR Could not find block with ID: xxx. Make sure the relevant pages and databases are shared with your integration.

What can be the problem?

**Comment by echo724** [comment]
Thank you for mentioning then issue. Can you explain the issue more specifically? You can give the url or id of the block if you don't mind or which block type that makes error occurred.

**Comment by pyMixin** [comment]
Sorry was able to resolve its was connection issue

**Comment by pyMixin** [comment]
However I am getting this error 

  Retrieved Notion blocks... (1.6s)
 Converting 2 blocks...

      ERROR 'text'
