### ISSUE TITLE
100 blocks limit

### ISSUE THREAD

**Issue by tiantiancoder** [echo724/notion2md#46]
hello~
I find that I can only get the first 100 blocks when I use notion2md to convert a notion page whose blocks is more than 100 blocks. And I want to know how to solve it?

**Comment by George3d6** [comment]
I've encountered this same issue, did you find any workaround?

**Comment by George3d6** [comment]
Ok, found the solution as a library edit, made a PR and testing myself now: https://github.com/echo724/notion2md/pull/47 (might take me 15 more mins to get it right)

**Comment by George3d6** [comment]
Tested, works!
