### ISSUE TITLE
pass in token as a parameter to MarkdownExporter

### ISSUE THREAD

**Issue by kevinco26** [echo724/notion2md#51]
Currently, there is no way to pass the Notion_Token as a parameter to the MarkdownExporter. This means that the only way for it to work in a python script is to set the environment variable to the correct notion_token.

Can we add notion_token as parameter to markdownexporter and check if it's passed use whatever was passed otherwise fetch from os.environ ?

This makes it hard to work with multiple notion keys in the same code.

**Comment by echo724** [comment]
Sounds Good. At that time I had no idea how to pass the token, but now I think this can be implemented by adding the token argument from cleo Command(block_command). Thank you for bring useful idea

**Comment by monaghancj** [comment]
Careful utilizing this to pass token's into the class, as the underlying class `NotionClient` is a `singleton`. This seems to result in new `tokens` being passed in getting ignore, potentially causing old tokens to be used during new requests.
