### ISSUE TITLE
No images exported

### ISSUE THREAD

**Issue by rathboma** [echo724/notion2md#6]
Hey, so happy I found this project! Looking to jump to a note-taking app that is more open.

Quick question. I'm exporting my page, but none of the images in the page are being exported. There's no `image` folder, and where the images were in the original notion page there is just empty space.

Any thoughts?

**Comment by rathboma** [comment]
example segment from a notion page:
![Screen Shot 2021-01-19 at 3 19 56 PM](https://user-images.githubusercontent.com/279769/105094395-d82fa880-5a69-11eb-8627-e7b78c55ca1c.png)

Output directory:

<img width="687" alt="Screen Shot 2021-01-19 at 3 20 36 PM" src="https://user-images.githubusercontent.com/279769/105094442-e8e01e80-5a69-11eb-8df0-96b06c4e50f5.png">


What the markdown file looks like (section is empty):

<img width="685" alt="Screen Shot 2021-01-19 at 3 21 09 PM" src="https://user-images.githubusercontent.com/279769/105094494-fac1c180-5a69-11eb-866f-3dc701dbc5b6.png">

**Comment by echo724** [comment]
Hi,

I tried to fix it, but it seems from the change of security rule from Notion(Not sure). It worked when using `request` python module. However, it is not working anymore.
